const sign = (
  id,
  file,
  vietnameseName,
  category,
  imageType,
  explanation,
  importantPoints,
) => ({ id, image: `./public/signs/${file}`, vietnameseName, japaneseName: null, category, imageType, explanation, importantPoints })

const signs = [
  sign(1, '1.png', 'Cấm quay đầu xe', 'Biển cấm', 'sign',
    'Biển này cấm xe thực hiện hành vi quay đầu để đổi sang hướng ngược lại trong phạm vi biển có hiệu lực. Biển chỉ quy định việc quay đầu, không tự động có nghĩa là cấm rẽ phải hay cấm rẽ trái; nếu tại đó có quy định cấm các hướng khác thì phải căn cứ vào biển hoặc vạch khác.',
    ['Cấm xe thực hiện hành vi quay đầu.', 'Không tự động có nghĩa là cấm rẽ phải hay cấm rẽ trái.']),
  sign(2, '2.webp', 'Vạch qua đường dành cho người đi bộ – dạng có hình học sinh', 'Biển chỉ dẫn', 'sign',
    'Đây là biển chỉ dẫn rằng tại vị trí đó có vạch qua đường dành cho người đi bộ. Về quy tắc lái xe: khi đến gần vạch qua đường, trừ khi rõ ràng không có người chuẩn bị qua, xe phải đi với tốc độ đủ để có thể dừng trước vạch. Nếu có người đang qua hoặc có ý định qua thì xe phải dừng trước vạch và nhường đường. Ngoài ra, tại vạch qua đường và trong phạm vi 30 m trước vạch có quy định riêng về vượt xe.',
    ['Xe phải đi với tốc độ đủ để có thể dừng trước vạch.', 'Nếu có người đang qua hoặc có ý định qua thì xe phải dừng trước vạch và nhường đường.', 'Trong phạm vi 30 m trước vạch có quy định riêng về vượt xe.']),
  sign(3, '3.jpg', 'Cấm dừng và cấm đỗ xe bằng vạch vàng ở mép đường', 'Vạch đường', 'road_marking',
    'Vạch vàng này là một dạng vạch quy định cấm dừng và cấm đỗ xe tại phần đường được đánh dấu. Xe không được chủ động dừng hoặc đỗ tại đó. Tuy nhiên, việc buộc phải dừng do đèn đỏ, tránh nguy hiểm hoặc do tình trạng giao thông không được coi là hành vi dừng/đỗ trái phép theo ý nghĩa của quy định này.',
    ['Xe không được chủ động dừng hoặc đỗ tại đó.', 'Buộc phải dừng do đèn đỏ, tránh nguy hiểm hoặc tình trạng giao thông là trường hợp khác.']),
  sign(4, '4.jpg', 'Cấm lấn sang phần đường bên phải để vượt xe', 'Biển cấm', 'sign',
    'Biển này cấm xe vì mục đích vượt xe phía trước mà lấn sang phần đường bên phải của đường. Điểm rất quan trọng là biển này không phải biển “cấm vượt hoàn toàn”. Điều bị cấm trực tiếp là việc vượt bằng cách chạy lấn sang phần đường bên phải. Nếu không phải lấn sang phần đường bên phải thì phải tiếp tục xét các quy định khác về vượt xe để biết có được vượt hay không.',
    ['Không phải biển “cấm vượt hoàn toàn”.', 'Cấm vượt bằng cách chạy lấn sang phần đường bên phải.']),
  sign(5, '5.jpg', 'Chỉ được đi thẳng', 'Biển chỉ dẫn', 'sign',
    'Biển chỉ định hướng đi. Xe không được đi theo hướng khác ngoài hướng mũi tên. Với hình trong folder của tiểu thư là mũi tên đi thẳng nên tại nơi biển có hiệu lực, xe phải đi thẳng; không được rẽ trái hoặc rẽ phải nếu không có chỉ dẫn khác cho phép.',
    ['Xe phải đi thẳng.', 'Không được rẽ trái hoặc rẽ phải nếu không có chỉ dẫn khác cho phép.']),
  sign(6, '6.webp', 'Đường một chiều', 'Biển chỉ dẫn', 'sign',
    'Biển quy định xe không được đi ngược lại hướng của mũi tên. Nói cách khác, phương tiện phải lưu thông theo chiều mũi tên của biển. Đây là quy định về chiều lưu thông của cả đoạn đường, khác với biển tròn chỉ định hướng phải đi ở một vị trí hoặc giao lộ.',
    ['Phương tiện phải lưu thông theo chiều mũi tên.', 'Quy định về chiều lưu thông của cả đoạn đường.']),
  sign(7, '7.jpg', 'Kết thúc phạm vi của quy định', 'Biển phụ', 'sign',
    'Đây là biển phụ, không có ý nghĩa độc lập. Nó cho biết quy định ghi trên biển chính gắn cùng biển phụ kết thúc tại vị trí đó. Các dạng như mũi tên kết thúc, chữ “đến đây” hoặc ký hiệu gạch chéo đều được dùng để biểu thị điểm kết thúc của phạm vi áp dụng.',
    ['Biển phụ không có ý nghĩa độc lập.', 'Quy định ghi trên biển chính kết thúc tại vị trí đó.']),
  sign(8, '8.png', 'Cấm đỗ xe từ 8 giờ đến 20 giờ', 'Biển cấm', 'sign',
    'Trong khoảng 08:00–20:00, xe không được đỗ trong phạm vi biển có hiệu lực. “Đỗ xe” gồm trường hợp xe dừng liên tục để chờ, hoặc người lái rời xe đến mức không thể lập tức điều khiển xe; việc cho người lên xuống xe hoặc bốc/dỡ hàng trong vòng 5 phút không được tính là đỗ xe theo định nghĩa này. Ngoài khung 8–20, riêng quy định thời gian trên biển này không áp dụng, nhưng vẫn phải tuân theo các quy định cấm đỗ khác nếu có.',
    ['Trong khoảng 08:00–20:00, xe không được đỗ.', 'Cho người lên xuống xe hoặc bốc/dỡ hàng trong vòng 5 phút không được tính là đỗ xe theo định nghĩa này.']),
  sign(9, '9.jpg', 'Xe máy nguyên động cơ loại thông thường phải rẽ phải theo hai giai đoạn', 'Biển chỉ dẫn', 'sign',
    'Khi biển này áp dụng, xe thuộc loại quy định phải rẽ phải theo cách hai giai đoạn: trước giao lộ phải đi gần về phía trái, từ khoảng 30 m trước giao lộ bật tín hiệu rẽ phải, khi đèn cho phép thì đi thẳng sang phía bên kia giao lộ, dừng lại, đổi hướng sang phải, tắt tín hiệu rẽ rồi chờ tín hiệu phía trước cho phép mới tiếp tục đi. Trong trường hợp phải rẽ hai giai đoạn thì không được dùng mũi tên xanh rẽ phải để rẽ trực tiếp.',
    ['Từ khoảng 30 m trước giao lộ bật tín hiệu rẽ phải.', 'Không được dùng mũi tên xanh rẽ phải để rẽ trực tiếp.']),
  sign(10, '10.png', 'Cấm tất cả lưu thông', 'Biển cấm', 'sign',
    'Biển này cấm người đi bộ, phương tiện điều khiển từ xa loại nhỏ, các loại xe và tàu điện chạy trên đường lưu thông qua đoạn đường đó. Vì vậy phạm vi của biển này rộng hơn biển “cấm xe lưu thông”.',
    ['Cấm người đi bộ, phương tiện điều khiển từ xa loại nhỏ, các loại xe và tàu điện chạy trên đường.', 'Phạm vi rộng hơn biển “cấm xe lưu thông”.']),
  sign(12, '12.jpg', 'Từ 8 giờ đến 20 giờ chỉ được đi thẳng hoặc rẽ trái', 'Biển chỉ dẫn', 'sign',
    'Trong thời gian ghi trên biển là 08:00–20:00, phương tiện chỉ được đi theo hai hướng được chỉ bằng mũi tên: đi thẳng hoặc rẽ trái. Không được đi theo hướng khác. Phần “8–20” là biển phụ giới hạn thời gian hiệu lực của quy định.',
    ['08:00–20:00 chỉ được đi thẳng hoặc rẽ trái.', 'Phần “8–20” giới hạn thời gian hiệu lực.']),
  sign(13, '13.png', 'Cấm người đi bộ băng qua đường', 'Biển cấm', 'sign',
    'Người đi bộ không được băng ngang qua phần đường có quy định này. Biển này không có nghĩa là cấm người đi bộ đi dọc theo đường hoặc vỉa hè; hành vi bị cấm là qua đường tại đoạn được quy định.',
    ['Cấm người đi bộ băng ngang qua đường.', 'Không có nghĩa là cấm người đi bộ đi dọc theo đường hoặc vỉa hè.']),
  sign(14, '14.jpg', 'Cấm xe lưu thông', 'Biển cấm', 'sign',
    'Biển này cấm các loại xe lưu thông qua đoạn đường đó. Theo cách dùng của luật giao thông Nhật, “xe” bao gồm ô tô, xe máy, xe đạp và các loại xe nhẹ thuộc phạm vi pháp luật. Người đi bộ không bị cấm chỉ vì có biển này, trừ khi có quy định khác. Vì vậy nó khác với số 10 là biển cấm tất cả lưu thông.',
    ['Cấm các loại xe lưu thông.', 'Người đi bộ không bị cấm chỉ vì có biển này.']),
  sign(15, '15.png', 'Giới hạn chiều cao 3,3 m', 'Biển cấm', 'sign',
    'Xe có chiều cao lớn hơn 3,3 m không được đi qua. Khi xác định chiều cao phải tính cả chiều cao của hàng hóa đang chở trên xe, không chỉ chiều cao thân xe.',
    ['Xe cao hơn 3,3 m không được đi qua.', 'Tính cả chiều cao của hàng hóa đang chở.']),
  sign(16, '16.jpg', 'Tín hiệu tay của cảnh sát khi giơ tay thẳng đứng', 'Tín hiệu cảnh sát', 'police_signal',
    'Khi cảnh sát hoặc người điều khiển giao thông giơ tay thẳng đứng: hướng giao thông chạy song song với mặt trước của cơ thể cảnh sát có ý nghĩa tương đương đèn vàng; hướng giao thông cắt ngang hướng đó có ý nghĩa tương đương đèn đỏ. Trong hình của tiểu thư, các xe đi theo hướng trước–sau của cảnh sát là phía phải dừng như đèn đỏ, còn hướng ngang bên trái–phải tương ứng với đèn vàng. Khi cảnh sát trực tiếp điều khiển giao thông thì phải tuân theo tín hiệu của cảnh sát.',
    ['Hướng song song với mặt trước cơ thể cảnh sát tương đương đèn vàng.', 'Hướng cắt ngang tương đương đèn đỏ.', 'Phải tuân theo tín hiệu của cảnh sát.']),
  sign(17, '17.png', 'Giới hạn tổng trọng lượng 5,5 tấn', 'Biển cấm', 'sign',
    'Xe có tổng trọng lượng lớn hơn 5,5 tấn không được đi qua. Đây là tổng trọng lượng của xe, không phải chỉ là trọng lượng hàng hóa đang chở.',
    ['Xe có tổng trọng lượng lớn hơn 5,5 tấn không được đi qua.', 'Không phải chỉ là trọng lượng hàng hóa.']),
  sign(18, '18.jpg', 'Giới hạn chiều rộng 2,2 m', 'Biển cấm', 'sign',
    'Xe có chiều cao, bao gồm cả hàng hóa, lớn hơn 2,2 m không được đi qua. Nguyên tắc giống số 14, chỉ khác trị số giới hạn.',
    ['Xe cao hơn 2,2 m không được đi qua.', 'Bao gồm cả hàng hóa.']),
  sign(19, '19.png', 'Cấm vượt xe', 'Biển cấm', 'sign',
    'Đây là biển cấm hành vi vượt xe. Vì vậy nó khác số 4: số 4 chỉ cấm lấn sang phần đường bên phải để vượt, còn biển này trực tiếp cấm việc vượt. Trong hệ thống biển Nhật, biển cấm vượt được thể hiện bằng biển chính kèm biển phụ ghi nội dung cấm vượt.',
    ['Trực tiếp cấm hành vi vượt xe.', 'Khác biển chỉ cấm lấn sang phần đường bên phải để vượt.']),
  sign(20, '20.png', 'Phân làn theo hướng đi', 'Biển chỉ dẫn', 'sign',
    'Biển quy định mỗi làn dành cho hướng đi nào tại giao lộ. Xe phải chọn và đi theo làn tương ứng với hướng mình muốn đi. Ví dụ làn có mũi tên trái dùng để rẽ trái, làn có mũi tên thẳng dùng để đi thẳng, làn có mũi tên phải dùng để rẽ phải theo nội dung thể hiện trên biển.',
    ['Xe phải chọn và đi theo làn tương ứng với hướng mình muốn đi.']),
  sign(21, '21.png', 'Tốc độ tối đa 50 km/h', 'Biển cấm', 'sign',
    'Tốc độ của phương tiện thuộc đối tượng áp dụng không được vượt quá 50 km/h. Con số trên biển là giới hạn tối đa, không phải tốc độ bắt buộc phải chạy.',
    ['Không được vượt quá 50 km/h.', 'Không phải tốc độ bắt buộc phải chạy.']),
  sign(22, '22.jpg', 'Cấm dừng và cấm đỗ xe', 'Biển cấm', 'sign',
    'Biển nền xanh có dấu X đỏ cấm cả dừng xe và đỗ xe. Khác với biển chỉ có một gạch chéo đỏ là “cấm đỗ”. Việc phải dừng vì đèn đỏ hoặc để tránh nguy hiểm là trường hợp khác, không phải hành vi tự ý dừng xe bị biển này cấm.',
    ['Cấm cả dừng xe và đỗ xe.', 'Dừng vì đèn đỏ hoặc tránh nguy hiểm là trường hợp khác.']),
  sign(23, '23.jpg', 'Cấm chuyển làn qua vạch vàng', 'Vạch đường', 'road_marking',
    'Đây là quy định cấm thay đổi hướng đi để chuyển từ làn này sang làn khác qua vạch vàng liền tại ranh giới làn xe. Nếu kiểu vạch được bố trí để chỉ cấm chuyển từ một phía sang phía kia thì phải nhìn đúng phía mà vạch áp dụng; không được suy ra rằng mọi hướng đều bị cấm nếu hình vạch chỉ quy định một chiều. Quy định chính thức của Nhật dùng vạch vàng liền tại ranh giới làn để thực hiện cấm chuyển làn.',
    ['Cấm chuyển làn qua vạch vàng liền.', 'Phải nhìn đúng phía mà vạch áp dụng.']),
  sign(24, '24.jpg', 'Cấm người đi bộ băng qua đường', 'Biển cấm', 'sign',
    'Ý nghĩa giống số 12: người đi bộ không được băng qua phần đường nằm trong phạm vi quy định. Đây là ảnh trùng nội dung nhưng vẫn giữ vì trong folder của tiểu thư đang có một ảnh riêng.',
    ['Người đi bộ không được băng qua phần đường nằm trong phạm vi quy định.', 'Ảnh trùng nội dung nhưng được giữ như một mục riêng.']),
  sign(25, '25.jpg', 'Đèn đỏ nhấp nháy', 'Đèn tín hiệu', 'traffic_light',
    'Đối với xe và tàu điện chạy trên đường, phải dừng hẳn tại vị trí dừng. Nếu có vạch dừng thì dừng ngay trước vạch; nếu không có vạch thì vị trí dừng được xác định theo giao lộ, vạch qua đường hoặc vị trí tín hiệu theo quy định. Sau khi dừng phải tiếp tục tuân theo quy tắc ưu tiên và chỉ đi khi an toàn.',
    ['Phải dừng hẳn tại vị trí dừng.', 'Sau khi dừng chỉ đi khi an toàn.']),
  sign(26, '26.jpg', 'Đèn vàng nhấp nháy', 'Đèn tín hiệu', 'traffic_light',
    'Xe, người đi bộ và tàu điện có thể tiếp tục đi, nhưng phải chú ý đến các phương tiện và người tham gia giao thông khác. Riêng tín hiệu vàng nhấp nháy không bắt buộc xe phải dừng hẳn.',
    ['Có thể tiếp tục đi nhưng phải chú ý.', 'Không bắt buộc xe phải dừng hẳn.']),
  sign(27, '27.jpg', 'Khu vực phải sử dụng còi', 'Biển chỉ dẫn', 'sign',
    'Biển còi kèm biển phụ chỉ đang ở trong đoạn áp dụng, nên đây là “khu vực phải sử dụng còi”, không phải cứ vào khu vực là bấm còi liên tục. Trong khu vực này phải bấm còi khi đi qua giao lộ bị khuất tầm nhìn, khúc cua bị khuất tầm nhìn hoặc đỉnh dốc lên bị khuất tầm nhìn. Ngoài các trường hợp pháp luật yêu cầu, được bấm còi khi thật sự cần để tránh nguy hiểm; còn các trường hợp khác thì không được tùy tiện bấm còi.',
    ['Không phải cứ vào khu vực là bấm còi liên tục.', 'Phải bấm còi tại giao lộ, khúc cua hoặc đỉnh dốc lên bị khuất tầm nhìn.']),
  sign(28, '28.png', 'Tín hiệu mũi tên vàng', 'Đèn tín hiệu', 'traffic_light',
    'Mũi tên màu vàng chỉ cho tàu điện chạy trên đường. Tàu điện có thể đi theo hướng mũi tên kể cả khi tín hiệu tròn đang vàng hoặc đỏ. Người đi bộ và các loại xe đường bộ không được đi chỉ vì mũi tên vàng đang sáng.',
    ['Mũi tên vàng chỉ cho tàu điện chạy trên đường.', 'Người đi bộ và xe đường bộ không được đi chỉ vì mũi tên vàng sáng.']),
  sign(29, '29.jpg', 'Khu vực cấm dừng xe trong ô', 'Vạch đường', 'road_marking',
    'Đây là phần đường được đánh dấu bằng các vạch trắng chéo. Xe không được đi vào nếu phía trước đang ùn tắc và có khả năng khiến xe phải dừng lại bên trong vùng này. Nếu có thể đi xuyên qua mà không bị mắc lại và không phải dừng trong vùng thì quy định này không cấm việc đi qua. Loại vạch này thường được dùng để giữ thông thoáng trước các vị trí như lối ra vào cơ quan khẩn cấp.',
    ['Không được đi vào nếu có khả năng phải dừng lại bên trong.', 'Có thể đi xuyên qua nếu không bị mắc lại và không phải dừng trong vùng.']),
  sign(30, '30.jpg', 'Được phép rẽ trái khi đèn đỏ hoặc vàng', 'Biển chỉ dẫn', 'sign',
    'Bảng nền trắng có mũi tên xanh sang trái cho phép xe rẽ trái kể cả khi tín hiệu phía trước đang đỏ hoặc vàng. Tuy nhiên, xe rẽ trái vẫn phải chú ý giao thông xung quanh và không được cản trở người đi bộ, xe đạp hoặc phương tiện đang được phép lưu thông theo tín hiệu của họ. Đây là bảng cho phép rẽ trái, không phải biển đường một chiều.',
    ['Được rẽ trái kể cả khi tín hiệu phía trước đang đỏ hoặc vàng.', 'Không được cản trở người đi bộ, xe đạp hoặc phương tiện đang được phép lưu thông.']),
  sign(31, '31.jpg', 'Phần đường cấm xe đi vào', 'Vạch đường', 'road_marking',
    'Phần được bao bằng đường viền vàng và các vạch trắng bên trong là khu vực xe không được đi vào và không được chạy qua. Điểm này khác hoàn toàn với số 28: số 28 chỉ không được đi vào nếu có nguy cơ phải dừng bên trong; còn phần cấm đi vào này thì bản thân việc chạy vào đã bị cấm.',
    ['Xe không được đi vào và không được chạy qua.', 'Bản thân việc chạy vào đã bị cấm.']),
  sign(32, '32.webp', 'Biển phụ chỉ điểm bắt đầu – đang trong đoạn – điểm kết thúc', 'Biển phụ', 'sign',
    'Ba dạng trong ảnh dùng để xác định phạm vi của biển chính: “từ đây” là điểm bắt đầu hiệu lực; mũi tên hai đầu thể hiện đang ở trong đoạn có hiệu lực; “đến đây” hoặc ký hiệu kết thúc thể hiện quy định kết thúc. Biển phụ không tự tạo ra quy định riêng mà phải đọc cùng biển chính phía trên.',
    ['“Từ đây” là điểm bắt đầu hiệu lực.', 'Mũi tên hai đầu là đang trong đoạn có hiệu lực.', '“Đến đây” thể hiện quy định kết thúc.']),
  sign(33, '33.jpg', 'Tín hiệu mũi tên xanh sang phải', 'Đèn tín hiệu', 'traffic_light',
    'Đối với ô tô thông thường, dù đèn tròn đang đỏ hoặc vàng, vẫn được đi theo hướng mũi tên xanh đang sáng. Với mũi tên sang phải, theo quy định hiện hành xe còn có thể quay đầu nếu việc quay đầu không bị cấm bởi quy định khác. Tuy nhiên, xe đạp, phương tiện cỡ nhỏ thuộc nhóm được luật quy định và xe máy nguyên động cơ phải rẽ phải hai giai đoạn không được rẽ phải theo mũi tên xanh sang phải này.',
    ['Ô tô thông thường vẫn được đi theo mũi tên xanh dù đèn tròn đỏ hoặc vàng.', 'Xe máy phải rẽ phải hai giai đoạn không được rẽ theo mũi tên này.']),
  sign(34, '34.jpg', 'Ký hiệu cấm quay đầu trên mặt đường', 'Vạch đường', 'road_marking',
    'Đây là vạch/ký hiệu trên mặt đường, không phải biển dựng bên đường. Ý nghĩa pháp lý là cấm xe quay đầu trong phạm vi được chỉ định. Nếu có con số kèm theo thì con số có thể dùng để chỉ khoảng thời gian việc quay đầu bị cấm.',
    ['Cấm xe quay đầu trong phạm vi được chỉ định.', 'Con số kèm theo có thể chỉ khoảng thời gian bị cấm.']),
]

window.SIGNS = signs
